//
//  PlayerStateAccessor.swift
//  PeacePlayer
//
//  Phase 2 / ios-qa: hand-rolled StateServer accessor registration for
//  PlayerState's @Snapshotable mirror properties.
//
//  The gstack `gen-accessors` codegen tool emits this file from
//  @Observable classes, but PlayerState is a legacy `ObservableObject`
//  (Combine). Rather than migrate the whole class — a 1758-line file
//  with hundreds of @Published bindings — we hand-roll the per-field
//  registration. The @Snapshotable mirror properties are stored values
//  (not @Published), so the read/write closures just touch them directly.
//
//  Why mirror properties at all? Because the @Snapshotable marker is
//  detected by attribute scan, but codegen also needs a stable
//  accessor-hash signature (the buildId + accessorHash args) for the
//  StateServer to detect schema changes. The mirror approach gives us
//  a separate, isolated read surface that doesn't change when the
//  @Published originals do.
//
//  Re-generated by hand whenever a new @Snapshotable field is added to
//  PlayerState. To migrate to auto-codegen, change PlayerState to
//  `@Observable` and run `gen-accessors --input ios`.
//

#if DEBUG

import Foundation
import CryptoKit

/// Not marked @MainActor because the public `register` is called from
/// PlayerState.init() which is not main-actor-isolated. The StateServer
/// itself is @MainActor, so the underlying register calls hop to main
/// thread internally. Read/write closures touch PlayerState properties
/// which are accessed on main thread by convention (PlayerState is a
/// UI singleton); we don't add any extra isolation here.
enum PlayerStateAccessor {

    /// Register the @Snapshotable mirrors on the given PlayerState
    /// instance with the StateServer. Idempotent: re-calling replaces
    /// the previous registration.
    static func register(_ state: PlayerState, buildId: String = "ios-1.0-debug") {
        // Hop to main actor. PlayerState is a UI singleton so its init
        // is always called on the main thread; the StateServer's
        // register methods are @MainActor-isolated, so we need this
        // hop. `MainActor.assumeIsolated` is the right call when we
        // know we're already on the main thread (avoids an async hop).
        MainActor.assumeIsolated {
        // Compute a stable schema hash from the field names + types.
        // The StateServer uses this to detect "old client talking to
        // new server" / "new client talking to old server" mismatches
        // and report a 409 instead of silently mis-routing writes.
        let accessorHash = computeAccessorHash()

        // We intentionally don't pass an `atomicRestore` closure here —
        // PlayerState doesn't expose a single `snapshotable` struct, and
        // for the ios-qa test plan we never need to restore. Restore is
        // only used by /state/restore and that's not in the test plan.
        StateServer.shared.register(
            buildId: buildId,
            accessorHash: accessorHash,
            atomicRestore: { _ in .ok }
        )

        // Per-field registration. The key is what the test agent sees at
        // GET /state/<key>. The type string is informational only
        // (for human-readable snapshots); reads and writes use the
        // closures directly.
        //
        // Enum values are exposed as String case names (via
        // `String(describing:)`) because NSJSONSerialization can't write
        // raw Swift enums — the previous attempt crashed the StateServer
        // with `objc_exception_throw` from `_writeJSONValue`. Strings are
        // the universal JSON currency; the test agent can compare like
        // `assert state.snapshotPlaybackState == "playing"`.
        StateServer.shared.registerAccessor(
            key: "snapshotPlaybackState",
            type: "String",
            read: { Self.playbackStateString(state.snapshotPlaybackState) },
            write: { value in
                guard let s = value as? String else { return false }
                guard let v = Self.playbackStateFromString(s) else { return false }
                state.snapshotPlaybackState = v
                return true
            }
        )
        StateServer.shared.registerAccessor(
            key: "snapshotContentType",
            type: "String",
            read: { Self.contentTypeString(state.snapshotContentType) },
            write: { value in
                guard let s = value as? String else { return false }
                guard let v = Self.contentTypeFromString(s) else { return false }
                state.snapshotContentType = v
                return true
            }
        )
        StateServer.shared.registerAccessor(
            key: "snapshotIsShuffled",
            type: "Bool",
            read: { state.snapshotIsShuffled as Any },
            write: { value in
                guard let v = value as? Bool else { return false }
                state.snapshotIsShuffled = v
                return true
            }
        )
        StateServer.shared.registerAccessor(
            key: "snapshotRepeatMode",
            type: "String",
            read: { state.snapshotRepeatMode.rawValue },
            write: { value in
                guard let s = value as? String else { return false }
                guard let v = RepeatMode(rawValue: s) else { return false }
                state.snapshotRepeatMode = v
                return true
            }
        )
        StateServer.shared.registerAccessor(
            key: "snapshotVolume",
            type: "Double",
            read: { state.snapshotVolume as Any },
            write: { value in
                guard let v = value as? Double else { return false }
                state.snapshotVolume = v
                return true
            }
        )
        StateServer.shared.registerAccessor(
            key: "snapshotPlaybackRate",
            type: "Float",
            read: { state.snapshotPlaybackRate as Any },
            write: { value in
                guard let v = value as? Float else { return false }
                state.snapshotPlaybackRate = v
                return true
            }
        )
        StateServer.shared.registerAccessor(
            key: "snapshotCurrentIndex",
            type: "Int",
            read: { state.snapshotCurrentIndex as Any },
            write: { value in
                guard let v = value as? Int else { return false }
                state.snapshotCurrentIndex = v
                return true
            }
        )
        } // MainActor.assumeIsolated
    }

    // MARK: - Enum <-> String conversion
    // JSON-only enum accessors. We avoid the JSONSerialization crash
    // (Swift enums can't be serialized as-is) by going through String.

    private static func playbackStateString(_ s: PlaybackState) -> String {
        switch s {
        case .idle: return "idle"
        case .loading: return "loading"
        // S17-H / S17-PLAY (Fix 6): new .transcoding state.
        case .transcoding: return "transcoding"
        case .playing: return "playing"
        case .paused: return "paused"
        case .buffering: return "buffering"
        case .error(let msg): return "error:\(msg)"
        }
    }

    private static func playbackStateFromString(_ s: String) -> PlaybackState? {
        if s == "idle" { return .idle }
        if s == "loading" { return .loading }
        if s == "playing" { return .playing }
        if s == "paused" { return .paused }
        if s == "buffering" { return .buffering }
        if s.hasPrefix("error:") { return .error(String(s.dropFirst("error:".count))) }
        return nil
    }

    private static func contentTypeString(_ c: PlaybackContentType) -> String {
        switch c {
        case .track: return "track"
        case .liveRadio: return "liveRadio"
        case .podcastEpisode: return "podcastEpisode"
        case .audiobook: return "audiobook"
        }
    }

    private static func contentTypeFromString(_ s: String) -> PlaybackContentType? {
        switch s {
        case "track": return .track
        case "liveRadio": return .liveRadio
        case "podcastEpisode": return .podcastEpisode
        case "audiobook": return .audiobook
        default: return nil
        }
    }

    /// Deterministic SHA-256 of the field-name + type-name set. Stays
    /// stable as long as the @Snapshotable surface is unchanged; changes
    /// whenever a field is added, removed, or has its type altered. The
    /// StateServer compares this against its own to detect schema drift.
    private static func computeAccessorHash() -> String {
        let fields: [(String, String)] = [
            ("snapshotContentType", "String"),
            ("snapshotCurrentIndex", "Int"),
            ("snapshotIsShuffled", "Bool"),
            ("snapshotPlaybackRate", "Float"),
            ("snapshotPlaybackState", "String"),
            ("snapshotRepeatMode", "String"),
            ("snapshotVolume", "Double"),
        ]
        let joined = fields.map { "\($0.0):\($0.1)" }.joined(separator: "|")
        let digest = SHA256.hash(data: Data(joined.utf8))
        return digest.map { String(format: "%02x", $0) }.joined()
    }
}

#endif // DEBUG
