//
//  KeychainHelper.swift
//  PeacePlayer
//
//  Minimal Keychain wrapper for storing the session JWT and
//  per-user metadata, plus the TimeCapsule master key.
//
//  iOS only — uses the kSecClassGenericPassword item class with
//  a constant service prefix so the items are scoped to this app.
//
//  2026-06-28 (initial)
//  2026-07-15 (S17-C CV-2): added Data-typed read/write and the
//  time-capsule master key path. The master key is a 256-bit
//  SymmetricKey generated by CryptoKit on first launch and stored
//  with kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly — same
//  accessibility class as the session token so background tasks
//  can decrypt capsules without prompting the user.
//

import Foundation
import Security
import CryptoKit

final class KeychainHelper {
    static let shared = KeychainHelper()
    private init() {}

    private let service = "com.peaceplayer.PeacePlayer"

    /// Separate service namespace for the time-capsule master key.
    /// Distinct from `service` so a future `deleteAll()` of the
    /// session items doesn't accidentally nuke the encryption key.
    private let timeCapsuleService = "com.ytaudioplayer.timecapsule"
    private let timeCapsuleKeyAccount = "timecapsule.master_key"

    // MARK: - Public API

    /// Returns the value for `key` or nil if the item is missing
    /// or the user denied access. Errors are logged but not thrown
    /// — Keychain failures shouldn't crash the app.
    func read(_ key: String) -> String? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: key,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne,
        ]
        var result: AnyObject?
        let status = SecItemCopyMatching(query as CFDictionary, &result)
        guard status == errSecSuccess, let data = result as? Data else {
            return nil
        }
        return String(data: data, encoding: .utf8)
    }

    /// Writes (or overwrites) the value at `key`.
    func write(_ key: String, _ value: String) {
        let data = Data(value.utf8)

        // First try to update an existing item.
        let updateQuery: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: key,
        ]
        let attributes: [String: Any] = [
            kSecValueData as String: data,
        ]
        let updateStatus = SecItemUpdate(updateQuery as CFDictionary, attributes as CFDictionary)

        if updateStatus == errSecSuccess { return }

        // No existing item — add a new one.
        if updateStatus == errSecItemNotFound {
            var addQuery: [String: Any] = updateQuery
            addQuery[kSecValueData as String] = data
            addQuery[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
            let addStatus = SecItemAdd(addQuery as CFDictionary, nil)
            if addStatus != errSecSuccess {
                #if DEBUG
                print("Keychain add failed for \(key): \(addStatus)")
                #endif
            }
        } else {
            #if DEBUG
            print("Keychain update failed for \(key): \(updateStatus)")
            #endif
        }
    }

    /// Removes the value at `key`. Silent if the item doesn't exist.
    func delete(_ key: String) {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: key,
        ]
        let status = SecItemDelete(query as CFDictionary)
        if status != errSecSuccess && status != errSecItemNotFound {
            #if DEBUG
            print("Keychain delete failed for \(key): \(status)")
            #endif
        }
    }

    /// Removes every key we own. Used by sign-out and tests.
    func deleteAll() {
        for key in [
            "peaceplayer.session_token",
            "peaceplayer.user_id",
            "peaceplayer.email",
            "peaceplayer.expires_at",
        ] {
            delete(key)
        }
    }

    // MARK: - Data-typed access (S17-C, CV-2)

    /// Returns the raw `Data` stored at `account` under
    /// `serviceName`, or nil if missing / denied.
    /// - Parameters:
    ///   - account: the per-item account name (like `key` in `read`)
    ///   - serviceName: the service namespace; defaults to the helper's
    ///     own service so session-token code and time-capsule code
    ///     stay separated.
    func readData(_ account: String, serviceName: String? = nil) -> Data? {
        let svc = serviceName ?? service
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: svc,
            kSecAttrAccount as String: account,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne,
        ]
        var result: AnyObject?
        let status = SecItemCopyMatching(query as CFDictionary, &result)
        guard status == errSecSuccess, let data = result as? Data else {
            return nil
        }
        return data
    }

    /// Stores raw `Data` at `account` under `serviceName`. If an
    /// item already exists it is updated in place. New items are
    /// written with `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly`
    /// so background tasks can read them and they do not sync to
    /// iCloud.
    @discardableResult
    func writeData(_ data: Data, account: String, serviceName: String? = nil) -> Bool {
        let svc = serviceName ?? service
        let updateQuery: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: svc,
            kSecAttrAccount as String: account,
        ]
        let attributes: [String: Any] = [
            kSecValueData as String: data,
        ]
        let updateStatus = SecItemUpdate(updateQuery as CFDictionary, attributes as CFDictionary)

        if updateStatus == errSecSuccess { return true }

        if updateStatus == errSecItemNotFound {
            var addQuery: [String: Any] = updateQuery
            addQuery[kSecValueData as String] = data
            addQuery[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
            let addStatus = SecItemAdd(addQuery as CFDictionary, nil)
            if addStatus != errSecSuccess {
                #if DEBUG
                print("Keychain add (data) failed for \(account) in \(svc): \(addStatus)")
                #endif
                return false
            }
            return true
        }

        #if DEBUG
        print("Keychain update (data) failed for \(account) in \(svc): \(updateStatus)")
        #endif
        return false
    }

    // MARK: - TimeCapsule master key (S17-C, CV-2)

    /// Returns the 256-bit symmetric key used to AES-GCM-encrypt
    /// TimeCapsule notes. If no key is stored yet, a fresh one is
    /// generated by CryptoKit and persisted before returning. The
    /// key is non-extractable from the Keychain on real devices —
    /// we just store the raw 32 bytes and wrap them back into a
    /// `SymmetricKey` on read.
    ///
    /// Returns nil only if the Keychain is locked in a way that
    /// the OS can't recover from — e.g. the user disabled the
    /// passcode. Callers should treat nil as "can't read or write
    /// any capsule right now" and surface a clear error.
    func getOrCreateTimeCapsuleMasterKey() -> SymmetricKey? {
        if let existing = readData(timeCapsuleKeyAccount, serviceName: timeCapsuleService) {
            if existing.count == 32 {
                return SymmetricKey(data: existing)
            }
            // Corrupted key of the wrong length — overwrite with a
            // fresh one. Old capsules encrypted with the old key
            // become unrecoverable, but the corruption itself is
            // the larger trust break so we don't try to keep both.
            #if DEBUG
            print("⚠️ TimeCapsule master key has wrong length (\(existing.count) bytes), regenerating")
            #endif
        }

        let newKey = SymmetricKey(size: .bits256)
        let rawBytes = newKey.withUnsafeBytes { Data($0) }
        guard writeData(rawBytes, account: timeCapsuleKeyAccount, serviceName: timeCapsuleService) else {
            return nil
        }
        return newKey
    }

    /// Removes the TimeCapsule master key. Existing encrypted
    /// capsules become unrecoverable. Intended for tests and the
    /// "wipe vault" debug menu — production sign-out does NOT call
    /// this because losing the key loses the user's history.
    func deleteTimeCapsuleMasterKey() {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: timeCapsuleService,
            kSecAttrAccount as String: timeCapsuleKeyAccount,
        ]
        let status = SecItemDelete(query as CFDictionary)
        if status != errSecSuccess && status != errSecItemNotFound {
            #if DEBUG
            print("Keychain delete (time capsule key) failed: \(status)")
            #endif
        }
    }
}
